version: 2.1

executors:
  buildpack:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo

jobs:
  build-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t az-cli .
      - run:
          name: Check kubectl
          command: docker run -it az-cli "which" "kubectl"
      - run:
          name: Check az
          command: docker run -it az-cli "az" "--version"
      - run:
          name: Check all versions
          command: |
            docker run -it az-cli "az"  "--version"
            echo "[kubectl] "$(docker run -it az-cli "kubectl"  "version" | head -n 1)
            echo "[python3] "$(docker run -it az-cli "python3"  "--version" | head -n 1)
            echo "[curl] "$(docker run -it az-cli "curl" "--version" | head -n 1)
            echo "[git] "$(docker run -it az-cli "git" "--version" | head -n 1)
            echo "[docker] "$(docker run -it az-cli "docker" "--version" | head -n 1)
            echo "[jq] "$(docker run -it az-cli "jq" "--version" | head -n 1)
            echo "[ytt] "$(docker run -it az-cli "ytt" "--version" | head -n 1)
            echo "[psql] "$(docker run -it az-cli "psql" "--version" | head -n 1)

  publish-latest-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build --target az_cli -t "aegirops/az-cli:latest" -t "aegirops/az-cli:${CIRCLE_TAG}" . --no-cache
            docker build --target az_cli_nodejs_18 -t "aegirops/az-cli:latest-node18" -t "aegirops/az-cli:${CIRCLE_TAG}-node18" .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aegirops/az-cli:latest
            docker push aegirops/az-cli:${CIRCLE_TAG}
            docker push aegirops/az-cli:latest-node14
            docker push aegirops/az-cli:${CIRCLE_TAG}-node14
            docker push aegirops/az-cli:latest-node16
            docker push aegirops/az-cli:${CIRCLE_TAG}-node16
            docker push aegirops/az-cli:latest-node18
            docker push aegirops/az-cli:${CIRCLE_TAG}-node18

workflows:
  build-test:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only:
                - /.*/

  publish:
    jobs:
      - publish-latest-docker-image:
          context: dockerGcloudCli
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
